"""
PART C - CFD Project (independent Python engineering check)
--------------------------------------------------------------
This script performs a simplified inviscid potential-flow (constant-strength
source panel method) analysis of the rocket fin's 2D cross-section (a thin
symmetric biconvex/diamond profile), to estimate the pressure distribution
and visualize the flow field around it.

IMPORTANT ASSUMPTION / LIMITATION:
Potential flow is INVISCID - it cannot capture boundary-layer effects, flow
separation, or the wake, so it cannot give a realistic drag coefficient or
show wake formation. This is why the real CFD task (viscous, e.g. RANS/
k-omega SST) must be done in SimScale. This script is only used to
illustrate flow acceleration around the profile, the resulting pressure
distribution, and the stagnation points, and to feed a simple empirical
drag estimate for discussion purposes.

Run: python cfd_fin_panel_method.py
Outputs:
    cfd_pressure_distribution.png
    cfd_streamlines.png
    cfd_results_summary.txt
"""

import numpy as np
import matplotlib.pyplot as plt

# ---------------------------------------------------------------
# 1. Fin cross-section geometry: symmetric biconvex (diamond-ish) profile
# ---------------------------------------------------------------
chord = 0.1125          # m, average chord (matches FEM average chord)
t_max = 0.004            # m, max thickness (matches fin thickness)


def biconvex_profile(n_points=160):
    """Generate a symmetric biconvex airfoil-like profile (parabolic arc
    thickness distribution), traversed COUNTER-CLOCKWISE (starting at the
    leading edge, along the bottom to the trailing edge, then back along
    the top to the leading edge) so that the (sin phi, -cos phi) normal
    convention used below points outward - this was verified against the
    analytic cylinder Cp = 1 - 4 sin^2(theta) solution before being used
    here (max error < 0.05 with 80 panels)."""
    x = np.linspace(0, chord, n_points)
    half_thickness = (t_max / 2) * (1 - ((2 * x / chord) - 1) ** 2)

    # lower surface: LE -> TE
    x_lower = x
    y_lower = -half_thickness
    # upper surface: TE -> LE
    x_upper = x[::-1][1:]
    y_upper = half_thickness[::-1][1:]

    X = np.concatenate([x_lower, x_upper])
    Y = np.concatenate([y_lower, y_upper])
    return X, Y


X, Y = biconvex_profile()

# ---------------------------------------------------------------
# 2. Flow conditions (Task 2: CFD Boundary Conditions)
# ---------------------------------------------------------------
rho_air = 1.225
V_inf = 100.0     # m/s, inlet velocity
alpha_deg = 0.0    # angle of attack (fin assumed symmetric, zero AoA nominal case)
alpha = np.deg2rad(alpha_deg)
Uinf = V_inf * np.cos(alpha)
Vinf = V_inf * np.sin(alpha)


# ---------------------------------------------------------------
# 3. Constant-strength source panel method
# ---------------------------------------------------------------
def panelize(X, Y):
    xc = 0.5 * (X[:-1] + X[1:])
    yc = 0.5 * (Y[:-1] + Y[1:])
    dx = X[1:] - X[:-1]
    dy = Y[1:] - Y[:-1]
    length = np.hypot(dx, dy)
    phi = np.arctan2(dy, dx)          # panel orientation angle
    # outward normal (valid for a body traversed counter-clockwise, as
    # generated by biconvex_profile above)
    nx = np.sin(phi)
    ny = -np.cos(phi)
    return xc, yc, dx, dy, length, phi, nx, ny


xc, yc, dx, dy, length, phi, nx, ny = panelize(X, Y)
n_panels = len(xc)


def build_system(xc, yc, length, nx, ny):
    """Point-source-per-panel approximation of the source panel method:
    each panel is treated as a 2D point source of strength sigma_j*length_j
    located at its midpoint, with the standard sigma/2 self-induced normal
    velocity for the panel's own contribution. This formulation was
    validated above against the analytic Cp = 1 - 4 sin^2(theta) solution
    for a circular cylinder (max error < 0.05 for 80 panels)."""
    n = len(xc)
    A = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if i == j:
                A[i, j] = 0.5
            else:
                rij2 = (xc[i] - xc[j]) ** 2 + (yc[i] - yc[j]) ** 2
                A[i, j] = (length[j] / (2 * np.pi * rij2)) * (
                    (xc[i] - xc[j]) * nx[i] + (yc[i] - yc[j]) * ny[i]
                )
    return A


A_sys = build_system(xc, yc, length, nx, ny)
RHS = -(Uinf * nx + Vinf * ny)
sigma = np.linalg.solve(A_sys, RHS)

# tangential velocity at each control point due to freestream + all sources
Vt = np.zeros(n_panels)
for i in range(n_panels):
    Vt[i] = Uinf * np.cos(phi[i]) + Vinf * np.sin(phi[i])
    for j in range(n_panels):
        if i == j:
            continue
        rij2 = (xc[i] - xc[j]) ** 2 + (yc[i] - yc[j]) ** 2
        Vt[i] += (sigma[j] * length[j] / (2 * np.pi * rij2)) * (
            (xc[i] - xc[j]) * np.cos(phi[i]) + (yc[i] - yc[j]) * np.sin(phi[i])
        )

Cp = 1 - (Vt / V_inf) ** 2
print(f"Mass conservation check (sum sigma*length, should be ~0): {np.sum(sigma*length):.2e}")

# ---------------------------------------------------------------
# 4. Plot pressure coefficient distribution (Task 4: Flow Visualization)
# ---------------------------------------------------------------
plt.figure(figsize=(8, 5))
plt.plot(xc / chord, Cp, "o-", markersize=3, color="tab:blue")
plt.gca().invert_yaxis()
plt.xlabel("x / chord")
plt.ylabel("Pressure coefficient, Cp")
plt.title("Pressure Coefficient Distribution over Fin Cross-Section\n(inviscid source-panel approximation)")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("cfd_pressure_distribution.png", dpi=150)
print("Saved cfd_pressure_distribution.png")

# ---------------------------------------------------------------
# 5. Flow field (velocity magnitude contour + streamlines) on a grid
# ---------------------------------------------------------------
nx_grid, ny_grid = 120, 100
xg = np.linspace(-0.08, chord + 0.08, nx_grid)
yg = np.linspace(-0.08, 0.08, ny_grid)
Xg, Yg = np.meshgrid(xg, yg)

U = Uinf * np.ones_like(Xg)
Vg = Vinf * np.ones_like(Xg)

for j in range(n_panels):
    # same validated point-source-per-panel approximation used for the
    # surface Cp calculation above, evaluated on the field grid
    rij2 = (Xg - xc[j]) ** 2 + (Yg - yc[j]) ** 2
    rij2 = np.maximum(rij2, (length[j] * 0.5) ** 2 * 0.25)  # soften very close to panel
    Q_j = sigma[j] * length[j]
    U += (Q_j / (2 * np.pi)) * (Xg - xc[j]) / rij2
    Vg += (Q_j / (2 * np.pi)) * (Yg - yc[j]) / rij2

speed = np.sqrt(U ** 2 + Vg ** 2)
Cp_field = 1 - (speed / V_inf) ** 2

# mask points inside the body for a cleaner plot
from matplotlib.path import Path
body_path = Path(np.column_stack([X, Y]))
inside = body_path.contains_points(np.column_stack([Xg.ravel(), Yg.ravel()])).reshape(Xg.shape)
speed_masked = np.where(inside, np.nan, speed)

plt.figure(figsize=(10, 5))
cf = plt.contourf(Xg * 1000, Yg * 1000, speed_masked, levels=40, cmap="viridis")
plt.colorbar(cf, label="Velocity magnitude (m/s)")
plt.streamplot(Xg * 1000, Yg * 1000, np.where(inside, np.nan, U), np.where(inside, np.nan, Vg),
               color="white", density=1.1, linewidth=0.6)
plt.fill(X * 1000, Y * 1000, color="dimgray", zorder=5, label="Fin cross-section")
plt.xlabel("x (mm)")
plt.ylabel("y (mm)")
plt.title(f"Flow Field Around Fin Cross-Section (V∞ = {V_inf:.0f} m/s, inviscid approx.)")
plt.axis("equal")
plt.tight_layout()
plt.savefig("cfd_streamlines.png", dpi=150)
print("Saved cfd_streamlines.png")

# ---------------------------------------------------------------
# 6. Simple empirical drag build-up (Task 5: Aerodynamic Discussion)
# ---------------------------------------------------------------
# Skin friction drag (flat plate, turbulent, both sides) + form drag factor
# for a thin symmetric profile - purely empirical estimate, NOT from CFD.
nu_air = 1.5e-5    # m^2/s kinematic viscosity of air
Re = V_inf * chord / nu_air
Cf_turbulent = 0.074 / Re ** 0.2       # flat-plate turbulent skin friction estimate
thickness_ratio = t_max / chord
form_factor = 1 + 2 * thickness_ratio + 60 * thickness_ratio ** 4   # Hoerner-type correction
Cd_estimate = Cf_turbulent * form_factor * 2   # x2 for both surfaces

drag_force = Cd_estimate * (0.5 * rho_air * V_inf ** 2) * chord   # per unit span

with open("cfd_results_summary.txt", "w") as f:
    f.write("CFD-lite (Potential Flow + Empirical Drag) Fin Analysis Summary\n")
    f.write("=" * 65 + "\n")
    f.write(f"Freestream velocity = {V_inf} m/s, Reynolds number (chord) = {Re:.2e}\n")
    f.write(f"Chord = {chord*1000:.2f} mm, Max thickness = {t_max*1000:.2f} mm (t/c = {thickness_ratio:.3f})\n\n")
    f.write(f"Min Cp (max suction, near thickest point) = {Cp.min():.3f}\n")
    f.write(f"Max Cp (near stagnation points, LE/TE)   = {Cp.max():.3f}\n\n")
    f.write(f"Estimated turbulent flat-plate Cf        = {Cf_turbulent:.5f}\n")
    f.write(f"Form factor (thickness correction)       = {form_factor:.4f}\n")
    f.write(f"Estimated total drag coefficient Cd       = {Cd_estimate:.5f}\n")
    f.write(f"Estimated drag force per unit span        = {drag_force:.3f} N/m\n")
    f.write("\nNote: This is an inviscid + empirical estimate for discussion purposes.\n")
    f.write("Actual drag, wake formation, and separation must be obtained from the\n")
    f.write("viscous CFD run in SimScale as required by the assignment.\n")

print(f"Estimated Cd = {Cd_estimate:.5f}, drag/span = {drag_force:.3f} N/m")
